services:
  postgres_db:
    image: postgres:15-alpine
    container_name: asistencia_facial_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin_password123
      POSTGRES_DB: sistema_asistencia
    ports:
      - "5439:5432"
    volumes:
      - pgdata_asistencia_v2:/var/lib/postgresql/data
volumes:
  pgdata_asistencia_v2:
